### ISSUE TITLE
New command New-BicepConfigJson to create bicepconfig.json file

### ISSUE THREAD

**Issue by StefanIvemo** [PSBicep/PSBicep#170]
**Describe the solution you'd like**
I want a command that creates the `bicepconfig.json` file to customize the behavior of the linter.

You should be able to do something like this:
```powershell
# Create a bicepconfig.json file setting all rules to warning
New-BicepConfigJson -Level Warning
```
This should create a `bicepconfig.json` in the current directory that looks like this:
```json
{
  "analyzers": {
    "core": {
      "rules": {
        "no-hardcoded-env-urls": {
          "level": "warning"
        },
        "no-unused-params": {
          "level": "warning"
        },
        "no-unused-vars": {
          "level": "warning"
        },
        "prefer-interpolation": {
          "level": "warning"
        },
        "secure-parameter-default": {
          "level": "warning"
        },
        "simplify-interpolation": {
          "level": "warning"
        }
      }
    }
  }
}
``` 
Or:
```powershell
# Create a bicepconfig.json file setting all rules set to error and store it in C:\myBiceps folder.
New-BicepConfigJson -Level Error -OutputDirectory 'C:\myBiceps\'
```

This should create a `bicepconfig.json` in the C:\myBiceps\ directory that looks like this:
```json
{
  "analyzers": {
    "core": {
      "rules": {
        "no-hardcoded-env-urls": {
          "level": "error"
        },
        "no-unused-params": {
          "level": "error"
        },
        "no-unused-vars": {
          "level": "error"
        },
        "prefer-interpolation": {
          "level": "error"
        },
        "secure-parameter-default": {
          "level": "error"
        },
        "simplify-interpolation": {
          "level": "error"
        }
      }
    }
  }
}
``` 

**Additional context**
https://github.com/Azure/bicep/blob/main/docs/linter.md
https://github.com/Azure/bicep/blob/main/src/Bicep.Core/Configuration/bicepconfig.json
https://github.com/Azure/bicep/blob/main/docs/examples/bicepconfig.json

**Comment by bjompen** [comment]
There seems to be a namespace in Bicep.Core that maintains and contains all rules that you can set in bicepconfig.json.

I am far from good in c#, but this might be usable to build a dynamic configuration based on what settings are currently supported?  Someone with better skills than me - feel free to chime in!

![bild](https://user-images.githubusercontent.com/17783007/124579092-1cafd480-de4f-11eb-8c87-08d2443fc614.png)

**Comment by bjompen** [comment]
I have managed to get a working version for review [here](https://github.com/bjompen/BicepPowerShell/blob/%23170_New-BicepConfigJson/Source/Public/New-BicepConfigJson.ps1),

however there are some things that I would like some feedback and help with:
- Currently it is hardcoded to add three levels of the resulting hashtables. while this is ok for now as there is always three levels of the configuration I would like to refactor this to a more dynamic solution, but my vacation brain cant figure out how to do this.
- The classes are currently hardcoded for bicep.dll, and should be rewritten to use the wrapped DLLs in 2.0
- Currently the command returns a json that can be piped to `out-file`, should we default to output a file, and have -AsJson as a switch instead? opinions?

**Comment by StefanIvemo** [comment]
I've done some testing now and it looks good overall. I ran `New-BicepConfigJson -Level Info | Out-File .\bicepconfig.json`. And the `bicepconfig.json` file was valid and worked with `Build-Bicep`. 

Using the latest version of the Bicep VS Code extension I do get some squigglies though.

Two new properties are now expected in the `bicepconfig.json`. We should set them to the default values below:
```json
"verbose": false,
"enabled": true,
```

And we should add parameters to set these values to true or false when creating the `bicepconfig.json` file. 

It also appears that the value for the `level` property is expected to be lower case by the VS Code extension. But it looks like you are loading the allowed diagnostics levels from Bicep.Core.
![image](https://user-images.githubusercontent.com/17688234/126702582-c171c30c-c452-4e49-a43d-8478e356094e.png)

I want to make sure that we output a file when the command is used and store it in the working directory with the option to change output directory. And of course verify if a `bicepconfig.json` is present and don't overwrite it.

**Comment by PalmEmanuel** [comment]
[BicepNet](https://github.com/PSBicep/BicepNet/) will also need to start using a bicepconfig.json file. Not the `analyzers` section, but the `cloud` part for URLs. We may want to decide the location of this file if the module will keep a copy, and ensure that both parts of the module handle the file well if so :)

**Comment by StefanIvemo** [comment]
You get a lot of help from the VSCode extension to create this file today. It provides intellisense for the user. Might not need this.

**Comment by StefanIvemo** [comment]
Closing this issue. It will be possible to create `bicepconfig.json` file with a click in VSCode. https://github.com/Azure/bicep/pull/6187
