### ISSUE TITLE
New-BicepParameterFile should have an -AsHashtable parameter

### ISSUE THREAD

**Issue by SimonWahlin** [PSBicep/PSBicep#174]
**Is your feature request related to a problem? Please describe.**
When generating bicep parameter files there might be a need of modifying the output before it is written to disk. Update-BicepParameterFile is an example of where it would come in handy.

**Describe the solution you'd like**
A new parameter set with a parameter called -AsHashtable that will return a hashtable instead of writing a paramterFile to disk.

**Additional context**
Should be implemented similiar to -AsHashtable on Build-Bicep

**Comment by StefanIvemo** [comment]
Closing this issue. Parameter files can now be generated using VSCode and we are getting closer to native bicep parameter files. I believe that folks will stop using this command.
