### ISSUE TITLE
Bicep documentation functionality

### ISSUE THREAD

**Issue by irwins** [PSBicep/PSBicep#223]
I stumbled across a tool [terraform-docs](https://github.com/terraform-docs/terraform-docs) while working with terraform. the tool makes it possible to generate md files, making documenting terraform modules files quite easy! 

It would great having this functionality to generate/update documentation of bicep files. Most of us are already glad when everything is working and don't spend much time documenting (I know shocking! 😁 )

I'm using the terraform-docs Markdown format manually but ideally would love to generate this JIT...

```Markdown
[[_TOC_]]
## Requirements

No requirements
## Providers

| name | version |
| --- | ---|
| Microsoft.Network/virtualNetworks | @2020-06-01 |
| Microsoft.Network/virtualNetworks/subnets | @2020-06-01 |
| Microsoft.Network/publicIPAddresses | @2020-06-01 |
| Microsoft.Network/azureFirewalls | @2020-06-01 |

## Resources

| Name | Type |
|------|------|
| [Microsoft.Network/virtualNetworks@2020-06-01 ](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/virtualnetworks?tabs=bicep) | resource |
| [Microsoft.Network/virtualNetworks/subnets@2020-06-01 ](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/virtualnetworks/subnets?tabs=bicep) | resource |
| [Microsoft.Network/publicIPAddresses@2020-06-01 ](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/publicipaddresses?tabs=bicep) | resource |
| [Microsoft.Network/azureFirewalls@2020-06-01 ](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/azurefirewalls?tabs=bicep) | resource |

## Inputs

| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| virtualNetworkName | virtualNetworkName | string | 'test-vnet' | no|
| vnetAddressPrefix | vnetAddressPrefix | string | '10.0.0.0/16' | no|
| azureFirewallSubnetAddressPrefix | azureFirewallSubnetAddressPrefix | string | '10.0.1.0/24'' | no|
| firewallName | firewallName | string | 'firewall1' | no|
| location | location | string | resourceGroup().location | no|
| availabilityZones | availabilityZones | array | ['1','2','3'] | no|
| tags | tags |  object |n/a|  yes|


## Outputs

n/a
```
![image](https://user-images.githubusercontent.com/10112589/137336748-78fd8c95-876d-48c0-9d97-70d0bded0943.png)

Having a well formatted generated ReadMe.md in the root of a module would make life so much easier for those who dread documentation... 😉

**Comment by StefanIvemo** [comment]
Cool! Can you create a PR and mark as draft instead? It's so much easier to test?

**Comment by bjompen** [comment]
Done. Created the documentation also. Still no tests though ;)

**Comment by irwins** [comment]
Holy crap that was quick! I'll try it out tomorrow 🙃👊🏾

**Comment by JohnRoos** [comment]
Let's have a look at tests and see if we can figure it out.
