### ISSUE TITLE
Add build on linux to the Github actions.

### ISSUE THREAD

**Issue by bjompen** [PSBicep/PSBicep#243]
Add build and run tests on linux as well as windows in the CI pipeline.

**Comment by StefanIvemo** [comment]
What do you want me to do @bjompen. Not following?

**Comment by Kaloszer** [comment]
@StefanIvemo 
Building on Windows and Linux with tests ensures that the module works in both envs.
Case sensitivity causes a lot of issues. for example:
Windows will work fine, but the Linux one will fail if there's a path hardcoded, but the case doesn't match.

**Comment by Kaloszer** [comment]
Added in #291 - so this can be closed.

**Comment by StefanIvemo** [comment]
Closes by #291
