### ISSUE TITLE
Generating parameter file from a bicep file containing default parameter values creates blank parameter file

### ISSUE THREAD

**Issue by Hardstl** [PSBicep/PSBicep#247]
Generating a parameter file using New-BicepParameterFile on a bicep template with default parameter values set creates an empty parameters file. Suggestion is to create the parameters, and if possible to also add the values from the bicep file.

1. Create bicep file with parameters that have a default value

Example:
```
param staName string = 'myStorageAccount'

resource storageaccount 'Microsoft.Storage/storageAccounts@2021-02-01' = {
  name: staName
  location: 'westeurope'
  kind: 'StorageV2'
  sku: {
    name: 'Premium_LRS'
  }
}
```

2. Run New-BicepParameterFile -Path <path to bicep file>

3. Empty parameters file is created

Example:
```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {}
}
```

Expected behaviour:
Create parameter file with values from bicep file.

Example:
```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "staName": {
      "value": ""
    }
  }
}
```

**Comment by StefanIvemo** [comment]
To add parameters with default values to your parameter file use the `-Parameters All` parameter with `New-BicepParameterFile`. Examples can be found here: https://github.com/PSBicep/PSBicep/blob/main/Docs/Help/New-BicepParameterFile.md

We are defaulting to only add required parameters to the parameter file.

A PR #237 is open for review to fix the case where an empty parameter file is created.
