### ISSUE TITLE
Action to build and publish module to PS Gallery

### ISSUE THREAD

**Issue by StefanIvemo** [PSBicep/PSBicep#260]
**Is your feature request related to a problem? Please describe.**
Module is published manually today. Without being built first. 

**Describe the solution you'd like**
Would like a new version of the module to be released to PS Gallery when a new release tag gets created. Should support prerelease as well. 

**Additional context**
Something to work from: https://github.com/PSBicep/BicepNet/blob/main/.github/workflows/build.yml

**Comment by SimonWahlin** [comment]
Done!
