### ISSUE TITLE
Add info about which `bicepconfig.json` file is being used to verbose output

### ISSUE THREAD

**Issue by StefanIvemo** [PSBicep/PSBicep#264]
**Is your feature request related to a problem? Please describe.**
Sometimes when you build or publish a bicep file you want to know which `bicepconfig.json` file is being used. 

**Describe the solution you'd like**
With the introduction of `Get-BicepNetConfig` in BicepNet [#35](https://github.com/PSBicep/BicepNet/pull/35), and the corresponding `Get-BicepConfig` we get the option to see which `bicepconfig.json` is being used for a specific bicep file, which is great. But I also see a value with adding this information to the verbose output of the following commands. It will simplify the end-user experience.

```powershell
Build-Bicep
Publish-Bicep
Restore-Bicep
```

Example:
```powershell
# No custom bicepconfig.json:

Build-Bicep -Path C:\Templates\Bicep\storage.bicep -Verbose
VERBOSE: Using Bicep version: 0.6.18.56646
VERBOSE: Using bicepconfig.json: Default

# Custom bicepconfig.json file:

Build-Bicep -Path C:\Templates\Bicep\storage.bicep -Verbose
VERBOSE: Using Bicep version: 0.6.18.56646
VERBOSE: Using bicepconfig.json: C:\Templates\Bicep\bicepconfig.json
```

**Comment by PalmEmanuel** [comment]
Love this suggestion, it's a no-brainer imo.
