### ISSUE TITLE
Publish-Bicep should throw failure on module publishing failure.

### ISSUE THREAD

**Issue by jambar42** [PSBicep/PSBicep#276]
**Describe the bug**
Publish-Bicep does not error when a module can't be published. This was encountered when ensuring module version immutability. 

**To Reproduce**
**1.** Publish a new bicep module to a container registry 
`Publish-Bicep -Path -.\mybicep.bicep -Target br:myacr.azurecr.io/mybicep:v1.2.3`
```
VERBOSE: Using Bicep version: 0.9.1.41621
VERBOSE: [mybicep.bicep] is valid
VERBOSE: [mybicep.bicep] published to: [br:myacr.azurecr.io/mybicep:v1.2.3]
```

**2.** Set the published module to `-WriteEnabled $False` to block any attempts to overwrite
`Update-AzContainerRegistryTag -RegistryName myacr -RepositoryName mybicep -Name v1.2.3 -DeleteEnabled $False -WriteEnabled $False -ReadEnabled $True -ListEnabled $True`
```
Registry     ImageName     Attributes
--------     ---------      ----------
myacr.azurecr.io mybicep Microsoft.Azure.Commands.ContainerRegistry.Models.PSTagAttributeBase
```

**3.** Verify that the tag is set as expected
`(Get-AzContainerRegistryTag -RegistryName myacr -RepositoryName mybicep -Name v1.2.3).Attributes.ChangeableAttributes`
```
DeleteEnabled WriteEnabled ListEnabled ReadEnabled
------------- ------------ ----------- -----------
        False        False        True        True
```

**4.** Publish the same module and version again.
`Publish-Bicep -Path -.\mybicep.bicep -Target br:myacr.azurecr.io/mybicep:v1.2.3` << This should error.
```
VERBOSE: Using Bicep version: 0.9.1.41621
VERBOSE: [mybicep.bicep] is valid
VERBOSE: [mybicep.bicep] published to: [br:myacr.azurecr.io/mybicep:v1.2.3]
```

**5.** Verify that a new version has not been published
`Get-AzContainerRegistryRepository -RegistryName myacr -Name mybicep`
```
Registry             : myacr.azurecr.io
ImageName            : mybicep
CreatedTime          : 2022-09-19T22:06:35.3042484Z
LastUpdateTime       : 2022-09-19T22:06:35.3042484Z
ManifestCount        : 1
TagCount             : 1
ChangeableAttributes : Microsoft.Azure.Commands.ContainerRegistry.Models.PSChangeableAttribute
```

**Expected behavior**
Publish-Bicep should fail when a module isn't able to be published.

**Additional context**
Step 2 above is being added to our CI/CD pipeline as the current module publishing implementation is not immutable by default.

 When running via bicep directly, an error is properly thrown.
 `bicep publish .\mybicep.bicep --target br:myacr.azurecr.io/mybicep:v1.2.3`
 ```Unable to publish module "br:myacr.azurecr.io/mybicep:v1.2.3": Service request failed.
Status: 405 (Method Not Allowed)

Content:
{"errors":[{"code":"REGISTRY_DISALLOWED_OPERATION","message":"The operation is disallowed on this registry, repository or image. View troubleshooting steps at https://aka.ms/acr/faq/#why-does-my-pull-or-push-request-fail-with-disallowed-operation-","detail":{}}]}```

**Comment by jambar42** [comment]
Related to [bicep publish should have an --immutable option](https://github.com/Azure/bicep/issues/8426)

**Comment by SimonWahlin** [comment]
This should be fixed in the next version of BicepNet and therefor also in next version of PSBicep
