### ISSUE TITLE
Add support for native Bicep parameter files

### ISSUE THREAD

**Issue by StefanIvemo** [PSBicep/PSBicep#284]
Bicep parameter files are soon to be released. We need to update the functionality in PSBicep to generate bicep parameter files instead of ARM parameter files. We need to discuss how we should do this. 

Thoughts:
- We should implement functionality to generate bicep param files and set this as the default behavior for all ways we can generate param files with PSBicep(New-BicepParameterFile, Build-Bicep). It should still be possible to generate an ARM parameter file.
- Update-BicepParameterFile should support both formats.

**Comment by SimonWahlin** [comment]
We should add this to BicepNet using the same logic as `bicep generate-params`

**Comment by SimonWahlin** [comment]
Closes as this was implemented in Build-BicepParam a long time ago
