### ISSUE TITLE
Add BicepNet as a required module

### ISSUE THREAD

**Issue by StefanIvemo** [PSBicep/PSBicep#286]
**Is your feature request related to a problem? Please describe.**
We should add BicepNet as a required module in the manifest instead of embedding the built module in PSBicep.

**Additional context**
Related issue in BicepNet [#54](https://github.com/PSBicep/BicepNet/issues/54)

**Comment by SimonWahlin** [comment]
We tried this, it was a compelling thought, but it would make all the *-BicepNet commands visible to the end user which was very confusing.
