### ISSUE TITLE
Add used modules in the .bicep file

### ISSUE THREAD

**Issue by Kaloszer** [PSBicep/PSBicep#292]
**Is your feature request related to a problem? Please describe.**

Modules used in a particular .bicep file should also be included. Along with their path to reference. 
In AzureDevOps we can reference said modules in a document repository - basically allowing us to link them together without having to navigate the whole folder structure to find it.

This should also allow us to generate a mermaidJs graph which shows dependencies, maybe sometime :)

**Describe the solution you'd like**
Expected output
``` md
## Modules

|Name|Path|
|----|----|
|somehelpermodule|modules\helpermodule.bicep|
```

## Modules

|Name|Path|
|----|----|
|somehelpermodule|modules\helpermodule.bicep|

**Additional context**
This is in regards to #223

Implemented on my branch. PR #293

**Comment by PalmEmanuel** [comment]
Implemented in #293
