### ISSUE TITLE
Add support for `--documentationUri` to `Publish-Bicep`

### ISSUE THREAD

**Issue by StefanIvemo** [PSBicep/PSBicep#294]
**Is your feature request related to a problem? Please describe.**
Bicep CLI have support to set a documentation URI when publishing Bicep modules to registries. 

`az bicep publish --file storage.bicep --target br:exampleregistry.azurecr.io/bicep/modules/storage:v1 --documentationUri https://www.contoso.com/exampleregistry.html`

**Describe the solution you'd like**
Add the parameter `-DocumentationUri ` to `Publish-Bicep`. 

**Additional context**
Dependency on BicepNet

**Comment by gogbg** [comment]
Any updates on that?

**Comment by SimonWahlin** [comment]
I think we have support for this in the underlaying C# code now, hope to have time to implement it in the public functions soon.
