### ISSUE TITLE
Add support for linter URLs in warnings

### ISSUE THREAD

**Issue by PalmEmanuel** [PSBicep/PSBicep#299]
**Describe the bug**
Warnings do not have urls appended to them in the same way as the CLI does.

**To Reproduce**
Use `bicep build` from the CLI on a file with something that the linter catches, and compare the result with `Build-BicepNetFile`. The 

---

![image](https://user-images.githubusercontent.com/17688234/163470037-886d2c9e-7f33-4a89-bfd6-25a7d217c010.png)

>Note: the warning comes from build

_Originally posted by @StefanIvemo in https://github.com/PSBicep/BicepNet/issues/29#issuecomment-1099592792_

**Comment by SimonWahlin** [comment]
![image](https://github.com/user-attachments/assets/52425718-0eb5-4b98-83c8-9d6ea0df845e)

Solved in previous version.
