### ISSUE TITLE
`Build-BicepNetParams` does not need a `-NoRestore` parameter

### ISSUE THREAD

**Issue by PalmEmanuel** [PSBicep/PSBicep#304]
**Describe the bug**
The `-NoRestore` parameter is unnecessary because you don't need to restore anything on .bicepparams files.

**Comment by SimonWahlin** [comment]
You don't need it today, but there's a feature in vNext where you can reference a modules from a registry directly in the bicepparam file so it might be needed in the future and it doesn't hurt to keep it in.
