### ISSUE TITLE
`Get-BicepNetCachePath` does not evaluate `cacheRootDirectory` in `bicepconfig.json`

### ISSUE THREAD

**Issue by StefanIvemo** [PSBicep/PSBicep#306]
**Describe the bug**
If I set a custom path for the module cache in `bicepconfig.json` using ` "cacheRootDirectory": "/Users/user1/bicepCache", `Get-BicepNetCachePath` still resolves to the default path.

**To Reproduce**
1. Set a custom path for the module cache by adding `cacheRootDirectory` to `bicepconfig.json`. 
2. Run `Get-BicepNetCachePath` 

**Expected behavior**
Get-BicepNetCachePath should look after custom cache location and return it.

**Additional context**

**Comment by SimonWahlin** [comment]
Interesting. For this to work I think we till need to add a -Path parameter where you supply a path to a bicep file, otherwise we won't know where to look for bicepconfig.json.

Would that be a good solution @StefanIvemo ?
