### ISSUE TITLE
Build-Bicep not working in github runner

### ISSUE THREAD

**Issue by Dylan-Prins** [PSBicep/PSBicep#319]
**Describe the bug**
![image](https://github.com/PSBicep/PSBicep/assets/8777848/7fb39021-042b-4e0b-b01c-1de43bdb9253)

**To Reproduce**
![image](https://github.com/PSBicep/PSBicep/assets/8777848/49c9c120-cfef-4f6e-9119-7c3cbf6003ba)

**Comment by SimonWahlin** [comment]
Hi @Dylan-Prins thanks for your report!
Which version of the module are you running? I'll try to reproduce later tonight.

**Comment by SimonWahlin** [comment]
I'm sorry, I can't seem to reproduce your error, would you min sharing a reproduction in a public repo?

![image](https://github.com/PSBicep/PSBicep/assets/5576847/7b86d54a-8ffe-4462-8c00-0724a29be7d5)
