### ISSUE TITLE
Publishing existing modules without `-Force` gives unclear error message

### ISSUE THREAD

**Issue by PalmEmanuel** [PSBicep/PSBicep#328]
**Describe the bug**

When implementing `-Force` for #296 I noticed that BicepNet gives a strange error when publishing modules that already exist.

**To Reproduce**

![image](https://github.com/PSBicep/PSBicep/assets/3384251/682bc99f-a36b-4539-b4ca-1ad384425059)

**Expected behavior**

A nice error saying that the module already exist would be much more user friendly.

**Comment by SimonWahlin** [comment]
This has been solved and now properly displays the error message similar to:

`Publish-Bicep: The module "br:myregistry.azurecr.io/bicep/main:v1" already exists in registry. Use --force to overwrite the existing module.`
