### ISSUE TITLE
API rate limit exceeded during build of bicep files in version 2.6.0

### ISSUE THREAD

**Issue by lassehastrup** [PSBicep/PSBicep#341]
**Describe the bug**

We have a lot of Bicep files that we are building using the cmdlet: '`Build-Bicep'` when we are testing our code using Pester.
After updating the bicep module to version 2.6.0 we are receiving a bunch of errors regarding API Rate limit.

Error we receive:

`API rate limit exceeded for **External IP address**). (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
`

We have about 100 bicep files that we build, which never have been an issue before, as this is the first time we experience this.
It seems to be an issue when running Invoke-RestMethod towards api.github.com, as this is the origin of the exception message:

`{
##[error]      "message": "API rate limit exceeded for **External IP** . (But here\u0027s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
##[error]      "documentation_url": "[https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"](https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting%22)
##[error]    }`

**To Reproduce**

I have a difficult time reproducing this locally, as we're using Selfhosted DevOps Agents and we only receive this error when our source is the Firewall behind the DevOps Agents.

**Expected behavior**
We don't expect to receive any errors when we are building the bicep files.

**Additional context**
In order to confirm that it is the bicep version 2.6.0 I manually configured the pester-job to use the previous version 2.5.0, and this works as expected.

If required, I can provide a list of bicep files, and the PowerShell script we use to build these files.

**Comment by SimonWahlin** [comment]
Hi @lassehastrup,

Just to confirm, is the file being built, but you are getting a lot of red text (non terminating errors) or does the build fail?

Seems like a problem with the check for new versions, mor specific this line:
https://github.com/PSBicep/PSBicep/blob/00091a64ad27bd400503d5eb8b438eb4444655ac/Source/Private/TestModuleVersion.ps1#L5

I'll try to reproduce and see if I can fix it with better error handling.

**Comment by lassehastrup** [comment]
Hi @SimonWahlin ,

Yea, it's a terminating error, so we don't get to process any of the files after they're compiled. We're simply stuck with the error.
Unfortunately, I think this will be hard to reproduce locally due to the rate limitations. Let me know if I can be of any help.

**Comment by PalmEmanuel** [comment]
Thanks for the info! We have a good idea of what the problem might be now, and are looking at a fix :)
